### ISSUE TITLE
Twitch.tv iframe unusable with extension enabled

### ISSUE THREAD

**Issue by Crecket** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#13]
Even when whitelisting twitch.tv the iframe that displays the actual stream is blacked out with a background. Probably caused by the iframe using a different site to serve the stream.

**Comment by SamFinni** [comment]
Curious why this was closed; it seems to still be an issue. Is it considered not a problem, or is a workaround known? This effects anyone who uses twitch.tv with this extension.
