### ISSUE TITLE
DuckDuckgo (non-JS version has no darkmode) renders ugly.

### ISSUE THREAD

**Issue by gitut2007** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#18]
Hi.
Firefox. 
In DuckDuckgo the links text becomes blue and on hover an ugly white background appears, also. the search box is unreadable. 
[you recommend using DDG own dark mode, but there's not one in no-JS version, and in JS maybe requires cookies to remember the setting])
Thanks.

**Comment by DarkNightMode** [comment]
Hi, 
We cannot support without javascript. Our algorithm won't work without javascript. 

Regards,
Vaibhav.
