### ISSUE TITLE
Is this caused by dark-night extension?

### ISSUE THREAD

**Issue by 211217613** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#19]
Notice the dark area in the search area.

![image](https://user-images.githubusercontent.com/7006850/46901805-4ccd1300-ce6f-11e8-99ae-3c8cda49e4d2.png)

**Comment by DarkNightMode** [comment]
Hi, 

Can you give us the website url ? 

Thanks, 
Vaibhav.

**Comment by 211217613** [comment]
After doing some research I came to the conclusion that Firefox for some reason picks up Ubuntu's 18.10 dark theme and makes all input fields look like that. 

I thought it had to do with extension but after disabling the extension the problem persisted.
