### ISSUE TITLE
Interest in using brain.js or machine learning for more dynamic dark or other project?

### ISSUE THREAD

**Issue by robertleeplummerjr** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#21]
Have been curious about this for some time.  I work on brain.js, and I would _love_ to have a dynamic engine that altered webpages based off my dynamic preferences.

Feel free to shoot down, and I already love this extension.

**Comment by DarkNightMode** [comment]
Hi Robert. 

Could you be more precise?
