### ISSUE TITLE
Update on the project status

### ISSUE THREAD

**Issue by JordyScript** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#22]
Hey! It would be nice if you could give us an update on the current status of the project. It has been 10 months since the latest commit, and you have cautioned developers/collaborators to not touch the code, cuz you are working on a newer version off Github that is yet in Beta. 

What is the progress on this beta version? and are you still working on the project or should we consider this project abandoned? Working on the project using Github will allow contributions from the community which would speed up development.

I for one would like to see a shortcut that can toggle dark mode on and off, which you have said is under construction in the FAQ, but contributing shortcuts isn't possible if this project is not being developed on Github.

**Comment by DarkNightMode** [comment]
Hi, 
We're working on a new version. It should be out in few weeks.
