### ISSUE TITLE
No dark mode on Facebook and Messenger.com

### ISSUE THREAD

**Issue by Kartm** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#23]
It might have been working a few days ago, but it looks broken now since Facebook introduced new chat colors. Also, the chat background is rendered very bright. I have also noticed that the backgrounds of the feed posts are affected as well. 

![facebook](https://user-images.githubusercontent.com/6399265/51146674-cfdb7c00-1857-11e9-887b-214198371534.png)
![chat](https://user-images.githubusercontent.com/6399265/51146675-cfdb7c00-1857-11e9-901e-5fa045824478.png)

**Comment by DarkNightMode** [comment]
Hi. 

Thanks, we've noted it down.
