### ISSUE TITLE
Suggestion: do not change background of images

### ISSUE THREAD

**Issue by Rubenmp** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#28]
There are images without background which change its color (i.e. http://mathworld.wolfram.com/SigmoidFunction.html)

![sigmoide](https://user-images.githubusercontent.com/11651356/57142622-4d060f00-6dbd-11e9-8c68-e9694e6c9b60.png)

It's strange because when "sigmoid function" is searched via google all images are well (they do not change even when there are no background)

**Comment by DarkNightMode** [comment]
Hi Rubenmp, 

It seems the issue is with transparent images only. We don't alter the background of images. 

Regards, 
Vaibhav.
