### ISSUE TITLE
Add time setting for auto mode

### ISSUE THREAD

**Issue by vertigo220** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#4]
Auto mode needs the ability to set the times for it to switch to and from night mode.

**Comment by dylan-k** [comment]
This feature is available in the latest version.
I found it in options > auto mode timings.
The options allow you to set the start and end times each day when the extension will run.

**Comment by texastoland** [comment]
The op is correct. The option exists but the schedule is hard-coded. The fix would be trivial but the project isn't active.
https://github.com/DarkNightMode/Dark-Night-Mode-Chrome-Extension/blob/2807a5f20a8fd5aa906a017e3bcbc212960816a8/js/main.js#L581
