### ISSUE TITLE
[Firefox] NoScript breaks dark mode on some websites

### ISSUE THREAD

**Issue by AffeAli** [DarkNightMode/Dark-Night-Mode-Chrome-Extension#8]
On some pages, if NoScript is blocking the JS of a site, the dark theme is only applied to some parts of the page.
Example:
https://docs.travis-ci.com/
JS blocked:
![](https://screenshotscdn.firefoxusercontent.com/images/d5e5aa85-a6bc-4837-96a8-74ba74bd3ea7.png)
not blocked:
![](https://screenshotscdn.firefoxusercontent.com/images/6ddbeb08-c220-4cff-93f5-9896b9530eae.png)

**Comment by rrohbeck** [comment]
Turning it off and back on, globally or with the whitelist button, makes it work even on a site where scripts are disabled with NoScript.
Could this be done automatically?
